# Generated by Django 5.2.16 on 2026-08-21 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0054_proposed_verb'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='SlackInstall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(max_length=32, unique=True)),
                ('team_name', models.CharField(blank=True, default='', max_length=200)),
                ('bot_token', models.CharField(max_length=255)),
                ('bot_user_id', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('installed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.orgmember')),
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slack_install', to='core.org')),
            ],
        ),
        migrations.CreateModel(
            name='SlackIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_user_id', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slack_identities', to='core.orgmember')),
                ('install', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='slack.slackinstall')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('install', 'slack_user_id'), name='uniq_slack_identity_per_install')],
            },
        ),
    ]
