# Generated by Django 5.2.16 on 2026-08-22 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackUnfurl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=32)),
                ('last_unfurled_at', models.DateTimeField(auto_now=True)),
                ('install', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unfurls', to='slack.slackinstall')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('install', 'ref'), name='uniq_slack_unfurl_per_ref')],
            },
        ),
    ]
