# Generated by Django 5.2.16 on 2026-07-11 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_backfill_orgs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to='core.org'),
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
