# Generated by Django 5.2.16 on 2026-07-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_activityevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='onboarding_dismissed',
            field=models.BooleanField(default=False),
        ),
    ]
