# Generated by Django 5.2.16 on 2026-07-13 10:54

import django.core.validators
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_user_managers_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$', 'invalid slug')]),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='slug',
            field=models.SlugField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$', 'invalid slug')]),
        ),
        migrations.AddConstraint(
            model_name='workspace',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('org'), name='uniq_ws_name_per_org'),
        ),
    ]
