# Generated by Django 5.2.16 on 2026-07-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_org_slug_alter_workspace_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='shipped_board_limit',
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='workspace',
            name='shipped_board_mode',
            field=models.CharField(choices=[('count', 'Count'), ('days', 'Days')], default='count', max_length=5),
        ),
    ]
