# Generated by Django 5.2.16 on 2026-07-14 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_workspace_shipped_board_limit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceStatSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('building_ct', models.IntegerField(default=0)),
                ('backlog_ct', models.IntegerField(default=0)),
                ('shipped_week_ct', models.IntegerField(default=0)),
                ('attention_ct', models.IntegerField(default=0)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_snapshots', to='core.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace', 'date'], name='core_worksp_workspa_2cccd2_idx')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'date'), name='uniq_ws_snapshot_per_day')],
            },
        ),
    ]
