# Generated by Django 5.2.16 on 2026-07-16 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityevent',
            name='verb',
            field=models.CharField(choices=[('created', 'created'), ('status_changed', 'status changed'), ('triaged', 'triaged'), ('moved', 'moved'), ('shipped', 'shipped'), ('dropped', 'dropped'), ('planned', 'planned')], max_length=20),
        ),
    ]
