# Generated by Django 5.2.16 on 2026-07-16 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_activityevent_verb'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='title',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='plan',
            name='slice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='core.slice'),
        ),
    ]
