# Generated by Django 5.2.16 on 2026-07-16 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_plan_title_alter_plan_slice'),
    ]

    operations = [
        migrations.AddField(
            model_name='bite',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bites', to='core.plan'),
        ),
        migrations.AlterField(
            model_name='bite',
            name='slice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bites', to='core.slice'),
        ),
    ]
