# Generated by Django 5.2.16 on 2026-07-16 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_bite_plan_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bite',
            name='slice',
        ),
        migrations.AlterField(
            model_name='bite',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bites', to='core.plan'),
        ),
    ]
