# Generated by Django 5.2.16 on 2026-07-17 11:02

import django.db.models.deletion
from django.db import migrations, models


def backfill_org_from_workspace(apps, schema_editor):
    """F() cannot traverse a relation inside update(), so drive the backfill
    from the Workspace side — one update() per workspace per model."""
    Workspace = apps.get_model("core", "Workspace")
    for ws in Workspace.objects.all().iterator():
        for model_name in ("Area", "Tag", "ApiToken", "ActivityEvent", "WorkspaceStatSnapshot"):
            Model = apps.get_model("core", model_name)
            Model.objects.filter(workspace=ws).update(org_id=ws.org_id)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_org_absorbs_workspace_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityevent',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='core.org'),
        ),
        migrations.AddField(
            model_name='apitoken',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='core.org'),
        ),
        migrations.AddField(
            model_name='area',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='core.org'),
        ),
        migrations.AddField(
            model_name='tag',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.org'),
        ),
        migrations.AddField(
            model_name='workspacestatsnapshot',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stat_snapshots', to='core.org'),
        ),
        migrations.RunPython(backfill_org_from_workspace, noop),
        migrations.AlterField(
            model_name='area',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='core.org'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.org'),
        ),
        migrations.AlterField(
            model_name='apitoken',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='core.org'),
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='core.org'),
        ),
        migrations.AlterField(
            model_name='workspacestatsnapshot',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_snapshots', to='core.org'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['org', '-created_at'], name='core_activi_org_id_afb032_idx'),
        ),
    ]
