# Generated by Django 5.2.16 on 2026-07-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_oauthclient_oauthauthorizationcode_oauthaccesstoken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='next_slice_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='slice',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
