# Generated by Django 5.2.16 on 2026-07-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_backfill_slice_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityevent',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='verb',
            field=models.CharField(choices=[('created', 'created'), ('status_changed', 'status changed'), ('triaged', 'triaged'), ('moved', 'moved'), ('shipped', 'shipped'), ('dropped', 'dropped'), ('planned', 'planned'), ('noted', 'noted')], max_length=20),
        ),
    ]
