# Generated by Django 5.2.16 on 2026-07-20 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_activityevent_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='slice',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_slices', to='core.orgmember'),
        ),
    ]
