# Generated by Django 5.2.16 on 2026-07-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_slice_assignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='slice',
            name='external_key',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
