# Generated by Django 5.2.16 on 2026-07-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_clear_copied_specs'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgmember',
            name='home_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
