# Generated by Django 5.2.16 on 2026-07-27 06:28

from django.db import migrations, models


def forward(apps, schema_editor):
    Slice = apps.get_model("core", "Slice")
    # 2026-07-27 실측 0건. 방어적으로 남긴다 — 이 릴리스 전에 누군가 켰을 수 있다.
    Slice.objects.filter(status="building").update(status="open")
    Slice.objects.filter(status="planned").update(status="open")


def backward(apps, schema_editor):
    # 되돌릴 때 open은 planned로 보낸다. building이었던 행은 복구 불가 —
    # 어느 open이 원래 building이었는지 남기지 않았다(0건이라 무의미).
    Slice = apps.get_model("core", "Slice")
    Slice.objects.filter(status="open").update(status="planned")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_activity_ref_format'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
        migrations.AlterField(
            model_name='slice',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('shipped', 'Shipped'), ('dropped', 'Dropped')], default='open', max_length=10),
        ),
    ]
