# Generated by Django 5.2.16 on 2026-07-27 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_slice_status_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='bite',
            name='slice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bites', to='core.slice'),
        ),
        migrations.AddField(
            model_name='slice',
            name='constraints',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='slice',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='core.slice'),
        ),
        migrations.AlterField(
            model_name='slice',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slices', to='core.area'),
        ),
        migrations.AddConstraint(
            model_name='slice',
            constraint=models.UniqueConstraint(condition=models.Q(('external_key', ''), _negated=True), fields=('org', 'external_key'), name='uniq_slice_external_key_per_org'),
        ),
    ]
