# Generated by Django 5.2.16 on 2026-08-10 08:23

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_schema_repair'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orgmember',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelManagers(
            name='orgmember',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='orgmember',
            name='ended_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
