# Generated by Django 5.2.16 on 2026-08-10 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_membership_ended_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityevent',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity', to='core.orgmember'),
        ),
    ]
