# Generated by Django 5.2.16 on 2026-08-01, hand-edited to add the dangling
# activity cleanup and the irreversibility guard.
"""Take down the safety net v0.44.0 left standing. Not reversible.

0045 folded the contents of Ticket and Plan into Slice but deliberately left
the tables in place — a few days of safety net, by decision. 0046 only
loosened Bite.plan to nullable; the column stayed. This migration actually
removes them:

- delete the activity events still typed 'ticket' (see forward())
- drop the Bite.plan column — its on_delete=CASCADE was the standing hazard:
  deleting one Plan row took a Slice's own steps with it
- DROP the Ticket and Plan tables

Imports no service code (apps.get_model() only), for the same reason as 0045:
when a migration calls a service, the day that service changes it silently
changes what an already-applied migration meant.
"""

from django.db import migrations, models


def forward(apps, schema_editor):
    """Delete the activity events 0045 could not move.

    ActivityEvent.target_type/target_id is a (string, int) pair, not a foreign
    key, so the database guarantees nothing about it. 0045 retargeted every
    event pointing at a ticket it folded, but left the ones pointing at
    tickets that had already been deleted before it ran — "nowhere to point,
    so leave them alone".

    Those rows are invisible everywhere today: slice_activity() and
    active_targets() both narrow target_type to slice/bite. Left in place they
    would survive forever holding a value this migration removes from the
    field's choices. By definition every remaining row is one of them, so
    there is no further condition to filter on.
    """
    Activity = apps.get_model("core", "ActivityEvent")
    deleted, _ = Activity.objects.filter(target_type="ticket").delete()
    if deleted:
        print(f"[0050] dangling_ticket_activity_deleted={deleted}")


def backward(apps, schema_editor):
    raise RuntimeError(
        "0050 cannot be reversed. Unapplying it would only have Django rebuild "
        "the Ticket/Plan tables EMPTY, and the deleted activity events do not "
        "come back either. Roll back with a Neon snapshot/branch restore."
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_activity_actor_to_source'),
    ]

    # RunPython goes first: clean up while target_type='ticket' still means
    # something, and make a failure there stop the run before anything
    # destructive has been touched.
    #
    # makemigrations also emitted a RemoveField for each of Ticket's four FKs
    # (area/created_by/org/slice) ahead of the DeleteModel. Those are dropped
    # on purpose. On SQLite a RemoveField rebuilds the whole table, and the
    # rebuild re-renders Ticket's UniqueConstraints and Indexes — every one of
    # which names `org`, the column being removed. Removing `org` therefore
    # crashed with "NewTicket has no field named 'org'" before anything else
    # ran. Nothing points AT Ticket, so the ordering those RemoveFields existed
    # to satisfy is vacuous: DeleteModel drops the table, its constraints and
    # its indexes in one step. Bite.plan still needs its own RemoveField —
    # that one is a live column on a table that survives.
    operations = [
        migrations.RunPython(forward, backward),
        migrations.RemoveField(
            model_name='bite',
            name='plan',
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='target_type',
            field=models.CharField(choices=[('slice', 'Slice'), ('bite', 'Bite'), ('area', 'Area')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
