# Generated by Django 5.2.16 on 2026-08-13 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_drop_tickets_and_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThrottleEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=300)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='throttle_episodes', to='core.org')),
            ],
            options={
                'ordering': ['-at'],
                'indexes': [models.Index(fields=['org', '-at'], name='core_thrott_org_id_9eca15_idx')],
            },
        ),
    ]
