# Generated by Django 5.2.16 on 2026-08-20 05:01

"""Every existing invitation gets NULL, and NULL is the true answer.

No backfill: there has never been a mail backend configured, and the one send
in the product passed fail_silently=True, so not one invitation in any existing
row was ever delivered. "Not emailed" is not a default here, it is the fact.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_throttle_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='emailed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
