# Generated by Django 5.2.16 on 2026-08-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_invitation_emailed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='slice',
            name='draft',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
