# Generated by Django 5.2.16 on 2026-08-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_slice_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityevent',
            name='verb',
            field=models.CharField(choices=[('created', 'created'), ('status_changed', 'status changed'), ('moved', 'moved'), ('shipped', 'shipped'), ('dropped', 'dropped'), ('planned', 'planned'), ('noted', 'noted'), ('proposed', 'proposed'), ('promoted', 'promoted'), ('dismissed', 'dismissed'), ('deleted', 'deleted'), ('triaged', 'triaged'), ('closed', 'closed')], max_length=20),
        ),
    ]
