# Generated by Django 5.2.16 on 2026-08-20 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_chose_verb'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('choice', models.CharField(blank=True, default='', max_length=200)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvas_watches', to='core.org')),
                ('slice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvas_watches', to='core.slice')),
            ],
        ),
    ]
