# Generated by Django 5.2.16 on 2026-08-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_canvas_watch'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvaswatch',
            name='question_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
