# Generated by Django 5.2.16 on 2026-08-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_slice_decision_tree'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='priority_policy',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='slice',
            name='priority',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
    ]
